version: '3.4'

services: 

  web:
    build: 
      context: musebackendserver
      target: base
    working_dir: /muse/muse
    command: 
      gunicorn muse.wsgi:application --bind 0.0.0.0:8000
    expose: 
      - "8000"
    env_file:
      - ./.env
    depends_on: 
      - db
      - spiders

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  spiders:
    build: 
      context: musebackendserver
      target: base
    working_dir: /muse/muse/spiders/lyricraper
    command: 
      ./entrypoint.sh
    ports:
      - "6800:6800"
    env_file:
      - ./.env

  modelserver:
    build:
      context: modelserver
      dockerfile: Dockerfile
    working_dir: /modelserver
    command: 
      ./startserver.sh
    expose: 
      - "5000"

  staticserve:
    build:
      context: muse-frontend
      dockerfile: Dockerfile
    working_dir: /muse
    ports:
      - "1337:80"

volumes: 
  postgres_data:
