# Generated by Django 3.1.2 on 2021-07-20 16:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('emptyLyricsSongIDs', models.CharField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=2000)),
                ('main_artist', models.CharField(max_length=2000)),
                ('artist_info', models.URLField(blank=True, max_length=2000, null=True)),
                ('all_artists', models.CharField(blank=True, max_length=2000, null=True)),
                ('album', models.CharField(blank=True, max_length=2000, null=True)),
                ('spotify_id', models.CharField(max_length=2000, unique=True)),
                ('album_art_lg', models.URLField(blank=True, max_length=2000, null=True)),
                ('album_art_md', models.URLField(blank=True, max_length=2000, null=True)),
                ('track_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('preview_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('lyrics', models.CharField(blank=True, max_length=20000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('spotifySeeds', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrackSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requestObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedTracks', to='endpoints.userrequest')),
                ('track', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='endpoints.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpotifyTrackSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requestObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selectedTracks', to='endpoints.recommendation')),
                ('track', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='endpoints.song')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='userRequest',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='endpoints.userrequest'),
        ),
    ]
