# Generated by Django 3.1.2 on 2021-06-25 06:01

import uuid
from django.db import migrations


def populateUUIDs(apps, schema_editor):
    Songs = apps.get_model('endpoints', 'Song')

    print('\nCreating UUIDs')
    for row in Songs.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

def depopulateUUIDs(apps, schema_editor):
    Songs = apps.get_model('endpoints', 'Song')

    print('\nNullifying UUIDs')
    for row in Songs.objects.all():
        row.uuid = None
        row.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0011_add_UUIDSongs'),
    ]

    operations = [
        migrations.RunPython(populateUUIDs, depopulateUUIDs)
    ]
