# Generated by Django 3.1.2 on 2021-06-25 19:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0013_populateRecommendationModel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytrackselection',
            old_name='trackID',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='usertrackselection',
            old_name='trackID',
            new_name='track',
        ),
        migrations.AlterField(
            model_name='song',
            name='uuid',
            field=models.UUIDField(primary_key=True, serialize=False),
        )
    ]
