# Generated by Django 3.1.2 on 2021-06-26 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('endpoints', '0014_addSongPK_renames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='spotifytrackselection',
            name='track',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='endpoints.song'),
        ),
        migrations.AlterField(
            model_name='usertrackselection',
            name='track',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, to='endpoints.song'),
        ),
    ]
