# Generated by Django 3.1.2 on 2021-06-27 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0017_make_spotifyID_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
