# Generated by Django 3.1.2 on 2021-07-01 06:38

from django.db import migrations

def NULL_string_lyrics_to_None(apps, schema_editor):
    Song = apps.get_model('endpoints', 'Song')
    objects = Song.objects.filter(lyrics__exact='NULL')
    for object in objects:
        object.lyrics = None
    Song.objects.bulk_update(objects, ['lyrics'])

class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0018_add_default_UUIDs'),
    ]

    operations = [
        migrations.RunPython(NULL_string_lyrics_to_None)
    ]
