# Generated by Django 3.1.2 on 2021-07-04 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0020_add_songID_tracking_for_spiders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='NLPRequest',
        ),
    ]
