# Generated by Django 3.1.2 on 2020-12-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='art',
            new_name='album_art_lg',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='artist',
            new_name='all_artists',
        ),
        migrations.AddField(
            model_name='songs',
            name='album_art_md',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='artist_info',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='main_artist',
            field=models.CharField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='preview_url',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='track_url',
            field=models.URLField(default=None, max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='lyrics',
            field=models.CharField(blank=True, max_length=20000),
        ),
    ]
