# Generated by Django 3.1.2 on 2020-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0006_auto_20201205_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='songqueryobject',
            name='recommendation_ids',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='songqueryobject',
            name='recommendations',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
