# Generated by Django 3.1.2 on 2021-06-25 12:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0009_remove_unused_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
    ]
