# Generated by Django 3.1.2 on 2021-07-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0019_remove_null_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='emptyLyricsSongIDs',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
