name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  health-check-job: 
    runs-on: ubuntu-18.04
    env:
      SPOTIFY_CLIENT_ID: 'test_client_id'
      SPOTIFY_CLIENT_SECRET: 'test_client_secret'
      SPOTIFY_AUTH_CODE: 'test_key'
      SPOTIFY_CLIENT_SECRET_BASE64: 'test_key'
      SPOTIFY_ACESS_TOKEN: 'test_key'

    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Cache python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install requirements
        run: pip install -r musebackendserver/requirements.txt

      - name: Run Migrations
        run: python musebackendserver/muse/manage.py migrate

      - name: Run Test
        run: python musebackendserver/muse/manage.py test apps.endpoints.tests && python musebackendserver/muse/manage.py test apps.nlp.tests
